version: '3.8'

services:
  mysqldb:
    image: mariadb:10.9.4
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PASS
      - MYSQL_PASSWORD=$DB_PASS
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./db:/docker-entrypoint-initdb.d #Crear las tablas automaticamente al iniciar
      - ./mysql:/var/lib/mysql #Mantener la misma data de mi base de datos local
  
  app:
    depends_on:
      mysqldb:
        condition: service_started
    build: 
      dockerfile: ./api/Dockerfile
    env_file: ./.env
    ports:
      - $BACK_PUBLIC_PORT:$BACK_PORT
    environment:
      - DB_HOST=mysqldb
    command: node dist/app.js
    volumes:
     - ./facturas:/app/facturas
     - ./remitos:/app/remitos

  front:
    depends_on:
      app:
        condition: service_started
    build:
      dockerfile: ./front/Dockerfile
    env_file: ./.env
    environment:
      - PORT=$FRONT_PORT
      - REACT_PROTOCOL=$PROTOCOL
      - REACT_APP_API_PORT=$BACK_PUBLIC_PORT
      - REACT_APP_HOST=$SERVER_HOST
      - HTTPS=true
      - SSL_KEY_FILE=security/key.pem
      - SSL_CRT_FILE=security/cert.pem

    command: npm start
    ports:
      - $FRONT_PUBLIC_PORT:$FRONT_PORT
    volumes:
     - ./facturas:/app/src/comprobantes/facturas
     - ./remitos:/app/src/comprobantes/remitos
