version: '3.8'

services:
  mysqldb:
    image: mariadb:10.9.4
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PASS
      - MYSQL_PASSWORD=$DB_PASS
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./db:/docker-entrypoint-initdb.d #Crear las tablas automaticamente al iniciar
      #- /var/lib/mysql:/var/lib/mysql #Mantener la misma data de mi base de datos local
      - ./mysql:/var/lib/mysql #Mantener la misma data de mi base de datos local
  
  app:
    depends_on:
      mysqldb:
        condition: service_started
    build: 
      dockerfile: ./api/Dockerfile
    env_file: ./.env
    ports:
      - $BACK_PORT:$BACK_PORT
    environment:
      - DB_HOST=mysqldb
    command: npm run dev
    #command: node src/app.js
    volumes:
     - ./api/dist/src:/app/src
     - ./facturas:/app/facturas
     - ./remitos:/app/remitos

  front:
    depends_on:
      app:
        condition: service_started
    build:
      dockerfile: ./front/Dockerfile
    env_file: ./.env
    environment:
      - PORT=$FRONT_PORT
      - REACT_APP_API_PORT=$BACK_PORT
      - REACT_APP_HOST=$SERVER_HOST
    command: npm start #serve -s build -l $FRONT_PORT
    ports:
      - 80:$FRONT_PORT
    volumes:
      - ./facturas:/app/src/comprobantes/facturas
      - ./remitos:/app/src/comprobantes/remitos
