name: Integration tests

on:
  push:
    branches: [ "main", "dev", "testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    services:
      mariadb:
        image: mariadb:10.9.4
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.DB_PASS }}.
          MARIADB_DATABASE: epublit_test
          MARIADB_USER: ${{ secrets.DB_USER }}
          MARIADB_PASSWORD: ${{ secrets.DB_PASS }}
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.8'

    - name: Load test data
      run:  mysql -h"127.0.0.1" -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} < ./db/test.sql

    - name: Show databases
      run:  mysql -h"127.0.0.1" -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} -e "SHOW DATABASES; USE epublit_test; SHOW TABLES;"
        
    - name: Prepare .env file
      run: echo "$ENV_FILE_CONTENT" > .env
      env:
        ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
       
    - name: Create files folders
      run: |
        mkdir -p files/facturas
        mkdir -p files/remitos
        mkdir -p files/logos

    - name: Create mock afip credentials
      run: |
        mkdir afipkeys
        cd afipkeys
        mkdir -p 20434919798/Tokens
        touch 20434919798/cert.pem 20434919798/private_key.key

        mkdir -p 27249804024/Tokens
        touch 27249804024/cert.crt 27249804024/private_key.key

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run:  npx jest
