# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
  
    env:
      SERVER_HOST: localhost
      DB_USER: user
      DB_PASS: password
      DB_PORT: 3306
      DB_NAME: db_name

      BACK_PORT: 3001
      FRONT_PORT: 3000

      JWT_SECRET: clave_secreta_segura
      JWT_EXPIRES_IN: 1h

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.9  # Cambia "14" por la versión de Node.js que estás utilizando

    - name: Build and start backend services
      run: |
        docker compose build app
        docker compose up -d app

    - name: Wait for backend to start
      run: sleep 15  # Asegúrate de esperar el tiempo necesario para que la API del backend esté lista para recibir peticiones

    - name: Install dependencies
      run: | 
        cd api
        npm install

    - name: Run tests
      run: |
        cd api
        npm run test

    - name: Stop and remove backend services
      run: docker compose down
