name: unit testing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  api-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    services:
      mysql:
        image: mysql:10.9.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: epublit_test
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.6 
        
    - name: Prepare .env file
      run: echo "$ENV_FILE_CONTENT" > .env
      env:
        ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        
    - name: Install dependencies
      run: | 
        cd api
        npm install

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --port=3306 --silent; do
        echo "Waiting for database connection..."
        sleep 1
        done
      env:
        MYSQL_PWD: Lautaro123.
    
    - name: Run tests
      run: |
        cd api
        npm run test
