name: unit testing

on:
  push:
    branches: [ "dev", "testing" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  api-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    services:
      mariadb:
        image: mariadb:10.9.4
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.DB_PASS }}.
          MARIADB_DATABASE: epublit_test
          MARIADB_USER: ${{ secrets.DB_USER }}
          MARIADB_PASSWORD: ${{ secrets.DB_PASS }}
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306
        volumes:
          - ./db:/docker-entrypoint-initdb.d
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.6 
        
    - name: Prepare .env file
      run: echo "$ENV_FILE_CONTENT" > .env
      env:
        ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        
    - name: Install dependencies
      run: | 
        cd api
        npm install

    - name: Run tests
      run: |
        cd api
        npx jest test/*
