name: unit testing

on:
  push:
    branches: [ "dev", "testing" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  api-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    services:
      mariadb:
        image: mariadb:10.9.4
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.DB_PASS }}.
          MARIADB_DATABASE: epublit_test
          MARIADB_USER: ${{ secrets.DB_USER }}
          MARIADB_PASSWORD: ${{ secrets.DB_PASS }}
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306
        volumes:
          - ./dbtest:/docker-entrypoint-initdb.d
    steps:
    - name: Show databases
      run:  mysql -h mariadb -uroot -p${{ secrets.DB_PASS }} -e "SHOW DATABASES"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.x'
        
    - name: Prepare .env file
      run: echo "$ENV_FILE_CONTENT" > .env
      env:
        ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

    - name: Load afip testing tokens
      run: |
        mkdir -p api/afipkeys/27249804024
        cd api/afipkeys/27249804024
        echo "$AFIP_CERT" > cert.crt
        echo "$AFIP_KEY" > private_key.key
      env:
        AFIP_CERT: ${{ secrets.AFIP_CERT }}
        AFIP_KEY: ${{ secrets.AFIP_KEY }}
        
    - name: Install dependencies
      run: | 
        cd api
        npm install

    - name: Run tests
      run: |
        cd api
        npx jest test/*
      env: 
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: 3306
        DB_NAME: epublit_test
