name: unit testing

on:
  push:
    branches: [ "dev", "testing" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  api-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    services:
      mariadb:
        image: mariadb:10.9.4
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.DB_PASS }}.
          MARIADB_DATABASE: epublit_test
          MARIADB_USER: ${{ secrets.DB_USER }}
          MARIADB_PASSWORD: ${{ secrets.DB_PASS }}
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306
        volumes:
          - ./dbtest:/docker-entrypoint-initdb.d
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.x'

    - name: Load test data
      run:  mysql -h"127.0.0.1" -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} < ./dbtest/test.sql

    - name: Show databases
      run:  mysql -h"127.0.0.1" -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} -e "SHOW DATABASES; USE epublit_test; SHOW TABLES;"
        
    - name: Prepare .env file
      run: echo "$ENV_FILE_CONTENT" > .env
      env:
        ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

    - name: Load afip testing tokens
      run: |
        mkdir -p api/afipkeys
        cd api/afipkeys
        mkdir -p 20434919798/Tokens
        echo "$AFIP_CERT" > 20434919798/cert.pem
        echo "$AFIP_KEY" > 20434919798/private_key.key
        sha1sum 20434919798/cert.pem
        sha1sum 20434919798/private_key.crt

        mkdir -p 27249804024/Tokens
        echo "$AFIP_CERT_PROD" > cert.crt
        echo "$AFIP_KEY_PROD" > private_key.key
        sha1sum 27249804024/cert.crt
        sha1sum 27249804024/private_key.key
        
      env:
        AFIP_CERT: ${{ secrets.AFIP_CERT }}
        AFIP_KEY: ${{ secrets.AFIP_KEY }}
        AFIP_CERT_PROD: ${{ secrets.AFIP_CERT_PROD }}
        AFIP_KEY_PROD: ${{ secrets.AFIP_KEY_PROD }}
        
    - name: Install dependencies
      run: | 
        cd api
        npm install

    - name: Start api
      run: |
        cd api
        npm run dev &
        echo $! > api.pid
        sleep 10

    - name: Run tests
      run: |
        cd api
        npx jest test/*
      env: 
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: 3306
        DB_NAME: epublit_test

    - name: Stop api
      run: kill $(cat api/api.pid) || true
